config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  resources :b_players
  resources :p_players
  resources :b_evaluations
  resources :p_evaluations
  resources :teams
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/b_evaluation.rb
class BEvaluation < ApplicationRecord
  belongs_to :b_player
end

app/models/b_player.rb
class BPlayer < ApplicationRecord
  has_many :b_evaluations
      validate :add_error_sample
 
  def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if name.blank?
      errors[:base] << "選手名は必ず入力して下さい！"
    end
  end
end

app/models/p_evaluation.rb
class PEvaluation < ApplicationRecord
  belongs_to :p_player
end

app/models/p_player.rb
class PPlayer < ApplicationRecord
  has_many :p_evaluations
    validate :add_error_sample
 
  def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if name.blank?
      errors[:base] << "選手名は必ず入力して下さい！"
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "プロ野球選手の評価チェック！"
  end
end

app/controllers/b_evaluations_controller.rb
class BEvaluationsController < ApplicationController
  def index
    @b_evaluations = BEvaluation.paginate(page: params[:page])
  end
  def new
    @b_evaluation = BEvaluation.new
  end
  def create
    @b_evaluation = BEvaluation.new(b_evaluation_params)
    if @b_evaluation.save
      flash[:info] = "評価完了しました。"
      redirect_to b_player_path(params[:b_evaluation][:b_player_id])
    else
      render 'new'
    end
  end
  def edit
    @b_evaluation = BEvaluation.find(params[:id])
  end
  def update
    @b_evaluation = BEvaluation.find(params[:id])
    if @b_evaluation.update_attributes(b_evaluation_params)
      flash[:info] = "選手の評価編集完了！"
       redirect_to b_player_path(params[:b_evaluation][:b_player_id])
    else
      render 'edit'
    end
  end
    private
    def b_evaluation_params
      params.require(:b_evaluation).permit(:b_player_id, :batting, :run, :shoulder, :defense, :text)
    end
end

app/controllers/b_players_controller.rb
class BPlayersController < ApplicationController
  def index
    @b_players = BPlayer.paginate(page: params[:page])
  end
  def show
    @b_player = BPlayer.find(params[:id])
    @b_evaluations = @b_player.b_evaluations.paginate(page: params[:page])
    @batting = @b_player.b_evaluations.average(:batting)
    @run = @b_player.b_evaluations.average(:run)
    @shoulder = @b_player.b_evaluations.average(:shoulder)
    @defense = @b_player.b_evaluations.average(:defense)
  end
  def new
    @b_player = BPlayer.new
  end
  def create
    @b_player = BPlayer.new(b_player_params)
    if @b_player.save
      flash[:info] = "選手を登録しました。"
      redirect_to b_players_path
    else
      render 'new'
    end
  end
  def edit
    @b_player = BPlayer.find(params[:id])
  end
  def update
    @b_player = BPlayer.find(params[:id])
    if @b_player.update_attributes(b_player_params)
       flash[:info] = "選手の編集完了！"
       redirect_to @b_player
    else
      render 'edit'
    end
  end
    private
    def b_player_params
      params.require(:b_player).permit(:name, :position, :team_id, :birthday, :graduate, :height, :weight, :blood_group, :handedness, :career, :year,)
    end
end

app/controllers/p_evaluations_controller.rb
class PEvaluationsController < ApplicationController
  def index
    @p_evaluations = PEvaluation.paginate(page: params[:page])
  end
  def new
    @p_evaluation = PEvaluation.new
  end
  def create
    @p_evaluation = PEvaluation.new(p_evaluation_params)
    if @p_evaluation.save
      flash[:info] = "評価完了しました。"
      redirect_to p_player_path(params[:p_evaluation][:p_player_id])
    else
      render 'new'
    end
  end
  def edit
    @p_evaluation = PEvaluation.find(params[:id])
  end
  def update
    @p_evaluation = PEvaluation.find(params[:id])
    if @p_evaluation.update_attributes(p_evaluation_params)
      flash[:info] = "選手の評価編集完了！"
       redirect_to p_player_path(params[:p_evaluation][:p_player_id])
    else
      render 'edit'
    end
  end
    private
    def p_evaluation_params
      params.require(:p_evaluation).permit(:p_player_id, :speed, :control, :breaking, :defense, :text)
    end
end

app/controllers/p_players_controller.rb
class PPlayersController < ApplicationController
  def index
    @p_players = PPlayer.paginate(page: params[:page])
  end
  def show
    @p_player = PPlayer.find(params[:id])
    @p_evaluations = @p_player.p_evaluations.paginate(page: params[:page])
    @speed = @p_player.p_evaluations.average(:speed)
    @control = @p_player.p_evaluations.average(:control)
    @breaking = @p_player.p_evaluations.average(:breaking)
    @defense = @p_player.p_evaluations.average(:defense)
  end
  def new
    @p_player = PPlayer.new
  end
  def create
    @p_player = PPlayer.new(p_player_params)
    if @p_player.save
      flash[:info] = "選手を登録しました。"
      redirect_to p_players_path
    else
      render 'new'
    end
  end
  def edit
    @p_player = PPlayer.find(params[:id])
  end
  def update
    @p_player = PPlayer.find(params[:id])
    if @p_player.update_attributes(p_player_params)
       flash[:info] = "選手の編集完了！"
       redirect_to @p_player
    else
      render 'edit'
    end
  end
    private
    def p_player_params
      params.require(:p_player).permit(:name, :position, :team_id, :birthday, :graduate, :height, :weight, :blood_group, :handedness, :career, :year,)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    @team = Team.find(params[:id])
    @p_player = PPlayer.where("team_id = ?", @team.id)
    @b_player = BPlayer.where("team_id = ?", @team.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "野球成績＆評価表"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
    def team_rename(team)
      return Team.find(team).name
    end
end

app/helpers/b_evaluations_helper.rb
module BEvaluationsHelper
end

app/helpers/b_players_helper.rb
module BPlayersHelper
end

app/helpers/p_evaluations_helper.rb
module PEvaluationsHelper
end

app/helpers/p_players_helper.rb
module PPlayersHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/b_evaluations/_b_evaluation.html.erb
<li id="b_evaluation-<%= b_evaluation.id %>">
  <span class="content">
  打撃<%= b_evaluation.batting %>P
  走力<%= b_evaluation.run %>P
  肩力<%= b_evaluation.shoulder %>P
  守備<%= b_evaluation.defense %>P
  <div class="button2"><%= link_to "評価編集する" ,edit_b_evaluation_path(b_evaluation.id) %></div>
  <br>
  <%= b_evaluation.text %>
  </span>
  <span class="timestamp">
  <%= b_evaluation.created_at.strftime("%Y年%m月%d日 %H時%M分") %>に投稿されました。
    <%#= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>  </span>
</li>

app/views/b_evaluations/edit.html.erb
<% provide(:title, '野手評価編集') %>
<h1>野手評価編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@b_evaluation) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"選手名" %>
      <%= f.collection_select :b_player_id,BPlayer.all, :id, :name, class: 'form-control' %>
      <br>
      <%= f.label :"打撃" %>
      <%= f.select :batting, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"走力" %>
      <%= f.select :run, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"肩力" %>
      <%= f.select :shoulder, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"守備" %>
      <%= f.select :defense, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"何かあればコメントどうぞ" %>
      <%= f.text_area :text %>
      <br>
      <%= f.submit "編集完了する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/b_evaluations/new.html.erb
<% provide(:title, '野手評価') %>
<h1>野手評価</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@b_evaluation) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"選手名" %>
      <%= f.collection_select :b_player_id,BPlayer.all, :id, :name, class: 'form-control' %>
      <br>
      <%= f.label :"打撃" %>
      <%= f.select :batting, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"走力" %>
      <%= f.select :run, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"肩力" %>
      <%= f.select :shoulder, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"守備" %>
      <%= f.select :defense, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"何かあればコメントどうぞ" %>
      <%= f.text_area :text %>
      <br>
      <%= f.submit "評価する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/b_players/_b_player.html.erb
<li>
  <%= link_to b_player.name,b_player %>
  <%= b_player.position %>
  <%= link_to team_rename(b_player.team_id),team_path(b_player.team_id) %>
</li>

app/views/b_players/edit.html.erb
<% provide(:title, '野手の編集') %>
<h1>野手の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@b_player) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"名前" %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :"ポジション" %>
      <%= f.select :position, [["捕手"],["一塁手"],["二塁手"],["三塁手"],["遊撃手"],["内野手"],["外野手"]],class: 'form-control' %>
      <%= f.label :"投打" %>
      <%= f.select :handedness, [["右投右打"],["右投左打"],["右投両打"],["左投右打"],["左投左打"],["左投両打"],["両投右打"],["両投左打"],["両投両打"]], :include_blank => true %>
      <%= f.label :"球団名" %>
      <%= f.collection_select :team_id,Team.all, :id, :name, class: 'form-control' %>
      <%= f.label :"プロ通算年数" %>
      <%= f.select :year, options_for_select((1..35).to_a), :include_blank => true %>年目
      <br>
      <%= f.label :"誕生日" %>
      <%= f.date_field :birthday, value: Time.now.strftime("%Y-%m-%d"), class: 'form-control' %>
      <%= f.label :"出身" %>
      <%= f.collection_select :graduate, JpPrefecture::Prefecture.all, :name, :name, :include_blank => true %>
      <br>
      <%= f.label :"経歴" %>
      <%= f.text_field :career, class: 'form-control' %>
      <%= f.label :"身長" %>
      <%= f.select :height, options_for_select((100..250).to_a), :include_blank => true %>cm
      <%= f.label :"体重" %>
      <%= f.select :weight, options_for_select((1..150).to_a), :include_blank => true %>kg
      <%= f.label :"血液型" %>
      <%= f.select :blood_group, [["A型"],["B型"],["O型"],["AB型"]], :include_blank => true %>
      <br>
      <%= f.submit "編集完了する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/b_players/index.html.erb
<% provide(:title, '野手一覧表') %>
<h1>野手一覧表</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @b_players %>
</ul>

<%= will_paginate %>

app/views/b_players/new.html.erb
<% provide(:title, '野手の追加') %>
<h1>野手の追加</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@b_player) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"名前" %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :"ポジション" %>
      <%= f.select :position, [["捕手"],["一塁手"],["二塁手"],["三塁手"],["遊撃手"],["内野手"],["外野手"],["投手"]],class: 'form-control' %>
      <%= f.label :"投打" %>
      <%= f.select :handedness, [["右投右打"],["右投左打"],["右投両打"],["左投右打"],["左投左打"],["左投両打"],["両投右打"],["両投左打"],["両投両打"]], :include_blank => true %>
      <%= f.label :"球団名" %>
      <%= f.collection_select :team_id,Team.all, :id, :name, class: 'form-control' %>
      <%= f.label :"プロ通算年数" %>
      <%= f.select :year, options_for_select((1..35).to_a), :include_blank => true %>年目
      <br>
      <%= f.label :"誕生日" %>
      <%= f.date_field :birthday, value: Time.now.strftime("%Y-%m-%d"), class: 'form-control' %>
      <%= f.label :"出身" %>
      <%= f.collection_select :graduate, JpPrefecture::Prefecture.all, :name, :name, :include_blank => true %>
      <br>
      <%= f.label :"経歴" %>
      <%= f.text_field :career, class: 'form-control' %>
      <%= f.label :"身長" %>
      <%= f.select :height, options_for_select((100..250).to_a), :include_blank => true %>cm
      <%= f.label :"体重" %>
      <%= f.select :weight, options_for_select((1..150).to_a), :include_blank => true %>kg
      <%= f.label :"血液型" %>
      <%= f.select :blood_group, [["A型"],["B型"],["O型"],["AB型"]], :include_blank => true %>
      <br>
      <%= f.submit "追加する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/b_players/show.html.erb
<% provide(:title, @b_player.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= @b_player.name %>
      </h1>
      <%= @b_player.position %>
      <%= @b_player.handedness %>
      <%= team_rename(@b_player.team_id) %>
      <%= @b_player.year %>年目
      <br>
      <%= @b_player.graduate %>出身
      <%= @b_player.career %>
      </br>
      <%= @b_player.birthday %>
      <%= @b_player.height %>cm
      <%= @b_player.weight %>kg
      <%= @b_player.blood_group %>
      <br>
      <br>
      <div class="button"><%= link_to "プロフィール編集する",edit_b_player_path(@b_player.id) %></div>
      <br>
<table align="" class="average" style="width:100%">
<colgroup>
<col style="width: 60%;" />
</colgroup>
  <thead>
    <tr>
<th scope="cols">評価項目</th>
<th scope="cols">平均点</th>
<tr>
<td>打撃</td>
<td>
  <% if @b_player.b_evaluations.any? %>
  <%= @batting.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</tr>
<tr>
<td>走力</td>
<td>
  <% if @b_player.b_evaluations.any? %>
  <%= @run.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</tr>
<tr>
<td>肩力</td>
<td>
  <% if @b_player.b_evaluations.any? %>
  <%= @shoulder.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</tr>
<td>守備</td>
<td>
  <% if @b_player.b_evaluations.any? %>
  <%= @defense.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</table>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @b_player.b_evaluations.any? %>
      <h4>評価数 (<%= @b_player.b_evaluations.count %>)</h4>
      <ol class="b_evaluations">
        <%= render @b_evaluations %>
      </ol>
      <%= will_paginate @b_evaluations %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    現職 <a href="https://goo.gl/kIXGhA">日本プロ野球コミッショナー</a>
     <a href="https://goo.gl/0AmoJx">熊崎勝彦</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://npb.jp/">日本野球機構</a></li>
      <li><a href="https://baseball.yahoo.co.jp/npb/">野球速報</a></li>
      <li><a href="https://baseball-mag.net/">baseball mag</a></li>
      <li><a href="http://yakyulive.web.fc2.com/">ネットで野球観戦</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "選手一覧＆評価表", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",   root_path %></li>
        <li><%= link_to "投手一覧表",   p_players_path %></li>
        <li><%= link_to "野手一覧表",   b_players_path %></li>
        <li><%= link_to "投手評価",   new_p_evaluation_path %></li>
        <li><%= link_to "野手評価",   new_b_evaluation_path %></li>
        <li><%= link_to "投手の追加", new_p_player_path %></li>
        <li><%= link_to "野手の追加", new_b_player_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/p_evaluations/_p_evaluation.html.erb
<li id="p_evaluation-<%= p_evaluation.id %>">
  <span class="content">
  球速 <%= p_evaluation.speed %>P
  コントロール<%= p_evaluation.control %>P
  変化球 <%= p_evaluation.breaking %>P
  守備 <%= p_evaluation.defense %>P
  <div class="button2"><%= link_to "評価編集する" ,edit_p_evaluation_path(p_evaluation.id) %></div>
  <br>
  <%= p_evaluation.text %>
  </span>
  <span class="timestamp">
  <%= p_evaluation.created_at.strftime("%Y年%m月%d日 %H時%M分") %>に投稿されました。
      <%#= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>  </span>
</li>

app/views/p_evaluations/edit.html.erb
<% provide(:title, '投手評価編集') %>
<h1>投手評価編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@p_evaluation) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"選手名" %>
      <%= f.collection_select :p_player_id,PPlayer.all, :id, :name, class: 'form-control' %>
      <br>
      <%= f.label :"球速" %>
      <%= f.select :speed, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"コントロール" %>
      <%= f.select :control, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"変化球" %>
      <%= f.select :breaking, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"守備" %>
      <%= f.select :defense, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"何かあればコメントどうぞ" %>
      <%= f.text_area :text %>
      <br>
      <%= f.submit "編集完了する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/p_evaluations/new.html.erb
<% provide(:title, '投手評価') %>
<h1>投手評価</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@p_evaluation) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"選手名" %>
      <%= f.collection_select :p_player_id,PPlayer.all, :id, :name, class: 'form-control' %>
      <br>
      <%= f.label :"球速" %>
      <%= f.select :speed, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"コントロール" %>
      <%= f.select :control, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"変化球" %>
      <%= f.select :breaking, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"守備" %>
      <%= f.select :defense, options_for_select((1..100).to_a), class: 'form-control' %>P
      <br>
      <%= f.label :"何かあればコメントどうぞ" %>
      <%= f.text_area :text %>
      <br>
      <%= f.submit "評価する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/p_players/_p_player.html.erb
<li>
  <%= link_to p_player.name,p_player %>
  <%= "投手" %>
  <%= link_to team_rename(p_player.team_id),team_path(p_player.team_id) %>
</li>

app/views/p_players/edit.html.erb
<% provide(:title, '投手の編集') %>
<h1>投手の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@p_player) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :"名前" %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :"投打" %>
      <%= f.select :handedness, [["右投右打"],["右投左打"],["右投両打"],["左投右打"],["左投左打"],["左投両打"],["両投右打"],["両投左打"],["両投両打"]], :include_blank => true %>
      <%= f.label :"球団名" %>
      <%= f.collection_select :team_id,Team.all, :id, :name, class: 'form-control' %>
      <%= f.label :"プロ通算年数" %>
      <%= f.select :year, options_for_select((1..35).to_a), :include_blank => true %>年目
      <br>
      <%= f.label :"誕生日" %>
      <%= f.date_field :birthday, value: Time.now.strftime("%Y-%m-%d"), class: 'form-control' %>
      <%= f.label :"出身" %>
      <%= f.collection_select :graduate, JpPrefecture::Prefecture.all, :name, :name, :include_blank => true %>
      <br>
      <%= f.label :"経歴" %>
      <%= f.text_field :career, class: 'form-control' %>
      <%= f.label :"身長" %>
      <%= f.select :height, options_for_select((100..250).to_a), :include_blank => true %>cm
      <%= f.label :"体重" %>
      <%= f.select :weight, options_for_select((1..150).to_a), :include_blank => true %>kg
      <%= f.label :"血液型" %>
      <%= f.select :blood_group, [["A型"],["B型"],["O型"],["AB型"]], :include_blank => true %>
      <br>
      <%= f.submit "編集完了する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/p_players/index.html.erb
<% provide(:title, '投手一覧表') %>
<h1>投手一覧表</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @p_players %>
</ul>

<%= will_paginate %>

app/views/p_players/show.html.erb
<% provide(:title, @p_player.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= @p_player.name %>
      </h1>
      <%= @p_player.position %>
      <%= @p_player.handedness %>
      <%= team_rename(@p_player.team_id) %>
      <%= @p_player.year %>年目
      <br>
      <%= @p_player.graduate %>出身
      <%= @p_player.career %>
      </br>
      <%= @p_player.birthday %>
      <%= @p_player.height %>cm
      <%= @p_player.weight %>kg
      <%= @p_player.blood_group %>
      <br>
      <br>
      <div class="button"><%= link_to "プロフィール編集する",edit_p_player_path(@p_player.id) %></div>
      <br>
<table align="" class="average" style="width:100%">
<colgroup>
<col style="width: 60%;" />
</colgroup>
  <thead>
    <tr>
<th scope="cols">評価項目</th>
<th scope="cols">平均点</th>
<tr>
<td>球速</td>
<td>
  <% if @p_player.p_evaluations.any? %>
  <%= @speed.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</tr>
<tr>
<td>コントロール</td>
<td>
  <% if @p_player.p_evaluations.any? %>
  <%= @control.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</tr>
<tr>
<td>変化球</td>
<td>
  <% if @p_player.p_evaluations.any? %>
  <%= @breaking.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</tr>
<td>守備</td>
<td>
  <% if @p_player.p_evaluations.any? %>
  <%= @defense.round(2) %>P
  <% else %>
評価なし
  <% end %>
  </td>
</table>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @p_player.p_evaluations.any? %>
      <h4>評価数 (<%= @p_player.p_evaluations.count %>)</h4>
      <ol class="p_evaluations">
        <%= render @p_evaluations %>
      </ol>
      <%= will_paginate @p_evaluations %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <h3> <%= pluralize(object.errors.count, "件のエラーがあります。") %></h3>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>プロ野球選手の評価</h1>

<h2>
    このサイトは１人１人が思う選手を各自評価し
  贔屓、アンチ関係なく皆平等に評価していただくサイトです。
  </h2>

<%= link_to image_tag("npb.jpg", alt: "npb logo"),
            'http://npb.jp/' %>